import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
// import { injectScript } from "my-script-injector";
// import { useEffect } from "react";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // injectScript('http://127.0.0.1:901/demo.js');
  // useEffect(() => {
  //   // 只在客户端注入脚本
  //   injectScript("http://127.0.0.1:901/demo.js");
  // }, []);
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
